# Generated by Django 3.2.15 on 2022-10-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_chorepage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choregroup',
            name='page',
        ),
        migrations.AddField(
            model_name='chorepage',
            name='groups',
            field=models.ManyToManyField(related_name='pages', to='chores.ChoreGroup'),
        ),
    ]
