# Generated by Django 3.2.15 on 2023-04-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_rename_frequency_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='chores.chore')),
            ],
        ),
    ]
