name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "main" ]

  push:
    branches: [ "master", "main" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Copy env
        run: cp .env.example .env

      - name: Pull old images
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml pull

      - name: Use layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the Stack
        run:  docker-compose -f docker-compose.yml -f docker-compose.ci.yml build

      - name: Run tests
        run:  docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm app make test

      - name: Tear down the Stack
        run:  docker-compose -f docker-compose.yml -f docker-compose.ci.yml down

  deploy:
    needs: test
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:

    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use layer caching
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build Docker image
      run: docker build -f .devops/django/Dockerfile -t $IMAGE_NAME --target python-run-stage .

    - name: Push Docker image
      run: docker push $IMAGE_NAME

    - name: Deploy Docker image
      run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region europe-central2 --platform managed
